import { NextRequest, NextResponse } from 'next/server';

const mockProjects = [
  {
    id: '1',
    year: 2025,
    deptName: '총무처',
    title: '캠퍼스 탄소중립 2030 로드맵 수립',
    category: 'ENVIRONMENT',
    task: '탄소중립 추진',
    thumbnail: 'https://images.unsplash.com/photo-1497436072909-60f360e1d4b1?w=600&q=80',
    oneLineSummary: '2030년까지 캠퍼스 탄소 배출량 50% 감축을 위한 단계별 실행 계획 수립',
    quantitative: '탄소 배출량 전년 대비 12% 감축 달성 (2,340톤 → 2,059톤)',
    qualitative: '캠퍼스 내 태양광 패널 설치, LED 조명 교체, 전기차 충전 인프라 구축 등 친환경 인프라 전환 사업을 체계적으로 추진하였습니다. 특히 건물 에너지 효율화 사업을 통해 냉난방 에너지 사용량을 크게 절감하였으며, 학생·교직원 대상 탄소중립 인식 제고 캠페인을 분기별로 시행하였습니다.',
    budget: 250000000,
    shortcoming: '일부 노후 건물의 에너지 효율화 공사가 예산 문제로 지연됨',
    improvement: '2026년 추가 예산 확보 및 정부 보조금 연계 사업으로 전환 추진',
    images: [],
    documents: [],
    isPublished: true,
    createdAt: '2025-03-15T00:00:00Z',
    updatedAt: '2025-03-15T00:00:00Z',
    userId: 'u1',
    user: { id: 'u1', email: 'admin@univ.ac.kr', deptName: '총무처' },
  },
  {
    id: '2',
    year: 2025,
    deptName: '학생처',
    title: '다문화 학생 지원 프로그램 운영',
    category: 'SOCIAL',
    task: '다문화 지원',
    thumbnail: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=600&q=80',
    oneLineSummary: '다문화 배경 학생의 학업 적응과 심리 상담을 위한 통합 지원 체계 구축',
    quantitative: '다문화 학생 멘토링 참여 120명, 만족도 4.7/5.0',
    qualitative: '다문화 학생 전담 상담사 배치, 한국어 튜터링 프로그램 운영, 문화 교류 행사를 정기적으로 개최하여 캠퍼스 내 다양성과 포용성을 증진하였습니다. 학업 중도 탈락률이 전년 대비 35% 감소하는 성과를 거두었습니다.',
    budget: 80000000,
    shortcoming: '비대면 상담 인프라가 부족하여 원격 학생 지원에 한계',
    improvement: '온라인 상담 플랫폼 도입 및 24시간 상담 핫라인 운영 계획',
    images: [],
    documents: [],
    isPublished: true,
    createdAt: '2025-04-10T00:00:00Z',
    updatedAt: '2025-04-10T00:00:00Z',
    userId: 'u2',
    user: { id: 'u2', email: 'student@univ.ac.kr', deptName: '학생처' },
  },
  {
    id: '3',
    year: 2025,
    deptName: '기획처',
    title: '대학 윤리경영 체계 고도화',
    category: 'GOVERNANCE',
    task: '윤리경영',
    thumbnail: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=600&q=80',
    oneLineSummary: '투명한 대학 운영을 위한 윤리경영 시스템 구축 및 내부 감사 체계 강화',
    quantitative: '윤리교육 이수율 98%, 내부 감사 시정 조치 이행률 95%',
    qualitative: '윤리경영위원회 운영을 정례화하고, 전 구성원 대상 윤리교육을 의무화하였습니다. 익명 제보 시스템을 도입하여 조직 내 부정행위를 사전에 예방하고, 내부 감사 결과를 홈페이지에 공개하여 경영 투명성을 강화하였습니다.',
    budget: 50000000,
    shortcoming: null,
    improvement: 'ESG 경영 통합 대시보드를 구축하여 실시간 모니터링 체계 마련',
    images: [],
    documents: [],
    isPublished: true,
    createdAt: '2025-05-01T00:00:00Z',
    updatedAt: '2025-05-01T00:00:00Z',
    userId: 'u3',
    user: { id: 'u3', email: 'plan@univ.ac.kr', deptName: '기획처' },
  },
  {
    id: '4',
    year: 2025,
    deptName: '시설관리처',
    title: '캠퍼스 생태 복원 및 녹지 확충',
    category: 'ENVIRONMENT',
    task: '생태복원',
    thumbnail: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=600&q=80',
    oneLineSummary: '캠퍼스 내 생태연못 조성 및 자생식물 정원 확충으로 생물다양성 증진',
    quantitative: '녹지 면적 15% 확대, 자생식물 50종 식재',
    qualitative: '캠퍼스 내 유휴 부지를 활용하여 생태연못과 습지원을 조성하고, 자생식물 정원을 확충하였습니다. 학생 참여형 생태모니터링 프로그램을 운영하여 환경 교육 기회를 제공하였습니다.',
    budget: 180000000,
    shortcoming: '생태 복원 지역의 유지관리 인력 부족',
    improvement: '학생 자원봉사단을 조직하여 지속가능한 관리 체계 구축',
    images: [],
    documents: [],
    isPublished: true,
    createdAt: '2025-06-01T00:00:00Z',
    updatedAt: '2025-06-01T00:00:00Z',
    userId: 'u4',
    user: { id: 'u4', email: 'facility@univ.ac.kr', deptName: '시설관리처' },
  },
  {
    id: '5',
    year: 2025,
    deptName: '대외협력처',
    title: '지역사회 상생 봉사 프로그램',
    category: 'SOCIAL',
    task: '사회공헌',
    thumbnail: 'https://images.unsplash.com/photo-1559027615-cd4628902d4a?w=600&q=80',
    oneLineSummary: '대학-지역사회 연계 봉사활동 및 재능기부 프로그램 운영',
    quantitative: '봉사활동 참여 학생 850명, 활동 시간 12,000시간',
    qualitative: '지역 소외 계층을 위한 교육 봉사, IT 기기 활용 교육, 독거노인 돌봄 서비스 등 다양한 봉사 프로그램을 운영하였습니다. 지역 중소기업과의 재능기부 협약을 통해 대학의 사회적 책임을 실천하였습니다.',
    budget: 45000000,
    shortcoming: null,
    improvement: '봉사 마일리지 제도를 도입하여 학생 참여 동기 강화',
    images: [],
    documents: [],
    isPublished: true,
    createdAt: '2025-07-01T00:00:00Z',
    updatedAt: '2025-07-01T00:00:00Z',
    userId: 'u5',
    user: { id: 'u5', email: 'external@univ.ac.kr', deptName: '대외협력처' },
  },
  {
    id: '6',
    year: 2025,
    deptName: '감사실',
    title: '정보공개 투명성 강화 사업',
    category: 'GOVERNANCE',
    task: '정보공개',
    thumbnail: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&q=80',
    oneLineSummary: '대학 경영 정보의 체계적 공개 및 이해관계자 소통 채널 확대',
    quantitative: '정보공개 건수 전년 대비 40% 증가, 이해관계자 만족도 4.5/5.0',
    qualitative: '경영공시 데이터를 시각화하여 홈페이지에 공개하고, 분기별 이해관계자 간담회를 개최하였습니다. 학생·학부모·교직원 대상 설문조사를 통해 정보공개 수요를 파악하고 맞춤형 정보를 제공하였습니다.',
    budget: 30000000,
    shortcoming: '영문 정보공개 콘텐츠 부족',
    improvement: '다국어 정보공개 시스템 구축 추진',
    images: [],
    documents: [],
    isPublished: true,
    createdAt: '2025-08-01T00:00:00Z',
    updatedAt: '2025-08-01T00:00:00Z',
    userId: 'u6',
    user: { id: 'u6', email: 'audit@univ.ac.kr', deptName: '감사실' },
  },
  {
    id: '7',
    year: 2024,
    deptName: '총무처',
    title: '에너지 절감형 스마트 캠퍼스 구축',
    category: 'ENVIRONMENT',
    task: '에너지 절감',
    thumbnail: 'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=600&q=80',
    oneLineSummary: 'IoT 기반 에너지 관리 시스템 도입으로 캠퍼스 에너지 효율 극대화',
    quantitative: '전력 사용량 18% 절감, 에너지 비용 연간 3억원 절약',
    qualitative: '건물별 IoT 에너지 모니터링 시스템을 설치하고, AI 기반 냉난방 자동 제어 시스템을 도입하였습니다. 전력 피크 시간대 자동 부하 관리로 전력 품질을 향상시켰습니다.',
    budget: 500000000,
    shortcoming: null,
    improvement: null,
    images: [],
    documents: [],
    isPublished: true,
    createdAt: '2024-09-01T00:00:00Z',
    updatedAt: '2024-09-01T00:00:00Z',
    userId: 'u1',
    user: { id: 'u1', email: 'admin@univ.ac.kr', deptName: '총무처' },
  },
  {
    id: '8',
    year: 2024,
    deptName: '학생처',
    title: '장애학생 학습권 보장 사업',
    category: 'SOCIAL',
    task: '장애학생 지원',
    thumbnail: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=600&q=80',
    oneLineSummary: '장애학생의 학습 접근성 향상을 위한 보조공학 기기 보급 및 지원 확대',
    quantitative: '보조공학 기기 50대 보급, 장애학생 만족도 4.8/5.0',
    qualitative: '장애 유형별 맞춤형 보조공학 기기를 지원하고, 강의실 접근성 개선 공사를 실시하였습니다. 장애학생 전담 튜터 제도를 확대하여 학업 지원을 강화하였습니다.',
    budget: 120000000,
    shortcoming: '온라인 강의 자막 지원이 부분적으로만 제공됨',
    improvement: 'AI 자동 자막 시스템 도입으로 전 강의 자막 지원 추진',
    images: [],
    documents: [],
    isPublished: true,
    createdAt: '2024-05-01T00:00:00Z',
    updatedAt: '2024-05-01T00:00:00Z',
    userId: 'u2',
    user: { id: 'u2', email: 'student@univ.ac.kr', deptName: '학생처' },
  },
  {
    id: '9',
    year: 2024,
    deptName: '기획처',
    title: 'ESG 경영 체계 도입',
    category: 'GOVERNANCE',
    task: 'ESG 경영',
    thumbnail: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&q=80',
    oneLineSummary: '대학 최초 ESG 경영 선언 및 추진 체계 수립',
    quantitative: 'ESG 위원회 설치, ESG 보고서 최초 발간',
    qualitative: 'ESG 경영 선포식을 개최하고, 총장 직속 ESG위원회를 설치하여 대학 전반의 ESG 경영을 총괄하는 체계를 구축하였습니다. 첫 ESG 연차보고서를 발간하여 대내외에 대학의 지속가능경영 의지를 공표하였습니다.',
    budget: 35000000,
    shortcoming: null,
    improvement: null,
    images: [],
    documents: [],
    isPublished: true,
    createdAt: '2024-03-01T00:00:00Z',
    updatedAt: '2024-03-01T00:00:00Z',
    userId: 'u3',
    user: { id: 'u3', email: 'plan@univ.ac.kr', deptName: '기획처' },
  },
];

export async function GET(request: NextRequest) {
  const { searchParams } = new URL(request.url);
  const year = searchParams.get('year');
  const category = searchParams.get('category');

  let filtered = mockProjects;

  if (year) {
    filtered = filtered.filter((p) => p.year === Number(year));
  }
  if (category) {
    filtered = filtered.filter((p) => p.category === category);
  }

  return NextResponse.json(filtered);
}
